[mHTTP GET /dashboard 200 [0.16, 127.0.0.1:20177][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:20184]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:20184]
Sat Mar 12 14:23:36 2022: Another client connected
Not Found: /favicon.ico
[33mHTTP GET /favicon.ico 404 [0.20, 127.0.0.1:20177][0m
[mHTTP GET /evaluate 200 [0.12, 127.0.0.1:20208][0m
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:20184]
[mHTTP GET /evaluate 200 [0.04, 127.0.0.1:20385][0m
[mHTTP GET /evaluate 200 [0.08, 127.0.0.1:20508][0m
[mHTTP GET /admin/ 200 [0.26, 127.0.0.1:20515][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.31, 127.0.0.1:20522][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:20522][0m
[mHTTP POST /admin/brewing/messurement/ 200 [0.10, 127.0.0.1:20527][0m
[mHTTP GET /static/admin/js/cancel.js 200 [0.03, 127.0.0.1:20527][0m
[32mHTTP POST /admin/brewing/messurement/ 302 [0.14, 127.0.0.1:20527][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.17, 127.0.0.1:20527][0m
[mHTTP GET /admin/jsi18n/ 200 [0.07, 127.0.0.1:20527][0m
Internal Server Error: /evaluate
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 451, in thread_handler
    raise exc_info[1]
  File "c:\users\jonas\documents\django\django\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\jonas\documents\django\django\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py", line 16, in evaluate
    for i in range(steps_number[0]['step']):
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 363, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
[35;1mHTTP GET /evaluate 500 [0.47, 127.0.0.1:20527][0m
[mHTTP GET /admin/brewing/messurement/add/ 200 [0.19, 127.0.0.1:20532][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:20532][0m
[32mHTTP POST /admin/brewing/messurement/add/ 302 [0.08, 127.0.0.1:20536][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.20, 127.0.0.1:20536][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:20536][0m
[mHTTP GET /admin/brewing/messurement/add/ 200 [0.14, 127.0.0.1:20536][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:20536][0m
[32mHTTP POST /admin/brewing/messurement/add/ 302 [0.08, 127.0.0.1:20542][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.19, 127.0.0.1:20542][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:20542][0m
[mHTTP GET /admin/brewing/messurement/add/ 200 [0.16, 127.0.0.1:20546][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:20546][0m
[32mHTTP POST /admin/brewing/messurement/add/ 302 [0.05, 127.0.0.1:20546][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.19, 127.0.0.1:20546][0m
[mHTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:20546][0m
[mHTTP GET /admin/brewing/messurement/add/ 200 [0.16, 127.0.0.1:20550][0m
[mHTTP GET /admin/jsi18n/ 200 [0.03, 127.0.0.1:20550][0m
[32mHTTP POST /admin/brewing/messurement/add/ 302 [0.05, 127.0.0.1:20556][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.23, 127.0.0.1:20556][0m
[mHTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:20556][0m
[mHTTP GET /evaluate 200 [0.05, 127.0.0.1:20556][0m
[mHTTP GET /evaluate 200 [0.11, 127.0.0.1:1903][0m
[mHTTP GET /evaluate 200 [0.05, 127.0.0.1:1926][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py changed, reloading.
[mHTTP GET /evaluate 200 [0.12, 127.0.0.1:1967][0m
[mHTTP GET /evaluate 200 [0.04, 127.0.0.1:1976][0m
[mHTTP GET /admin/brewing/messurement/add/ 200 [0.19, 127.0.0.1:1992][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:1992][0m
[32mHTTP POST /admin/brewing/messurement/add/ 302 [0.05, 127.0.0.1:1999][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.22, 127.0.0.1:1999][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:1999][0m
[mHTTP GET /evaluate 200 [0.06, 127.0.0.1:2005][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py changed, reloading.
[mHTTP GET /evaluate 200 [0.15, 127.0.0.1:2040][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py changed, reloading.
Internal Server Error: /evaluate
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 451, in thread_handler
    raise exc_info[1]
  File "c:\users\jonas\documents\django\django\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\jonas\documents\django\django\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py", line 17, in evaluate
    for i in range(steps_number[0]):
TypeError: 'dict' object cannot be interpreted as an integer
[35;1mHTTP GET /evaluate 500 [0.25, 127.0.0.1:2107][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py changed, reloading.
Internal Server Error: /evaluate
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 451, in thread_handler
    raise exc_info[1]
  File "c:\users\jonas\documents\django\django\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\jonas\documents\django\django\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py", line 17, in evaluate
    for i in range(steps_number):
TypeError: 'QuerySet' object cannot be interpreted as an integer
[35;1mHTTP GET /evaluate 500 [0.24, 127.0.0.1:2141][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py changed, reloading.
[mHTTP GET /evaluate 200 [0.14, 127.0.0.1:2165][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py changed, reloading.
[mHTTP GET /evaluate 200 [0.14, 127.0.0.1:2216][0m
Internal Server Error: /evaluate
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 451, in thread_handler
    raise exc_info[1]
  File "c:\users\jonas\documents\django\django\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\jonas\documents\django\django\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py", line 31, in evaluate
    return render(request, 'brewing/evaluate.html', {
  File "c:\users\jonas\documents\django\django\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\jonas\documents\django\django\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\jonas\documents\django\django\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\jonas\documents\django\django\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\jonas\documents\django\django\django\template\engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\jonas\documents\django\django\django\template\engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\jonas\documents\django\django\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\jonas\documents\django\django\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\jonas\documents\django\django\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\jonas\documents\django\django\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\jonas\documents\django\django\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\jonas\documents\django\django\django\template\defaulttags.py", line 853, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "c:\users\jonas\documents\django\django\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "c:\users\jonas\documents\django\django\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '['pretty']' from 'dates['pretty']'
[35;1mHTTP GET /evaluate 500 [0.30, 127.0.0.1:2282][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py changed, reloading.
C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py changed, reloading.
[mHTTP GET /evaluate 200 [0.15, 127.0.0.1:2378][0m
[mHTTP POST /evaluate 200 [0.04, 127.0.0.1:2387][0m
[mHTTP GET /admin/brewing/messurement/add/ 200 [0.24, 127.0.0.1:2387][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:2387][0m
[32mHTTP POST /admin/brewing/messurement/add/ 302 [0.07, 127.0.0.1:2402][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.23, 127.0.0.1:2402][0m
[mHTTP GET /admin/jsi18n/ 200 [0.07, 127.0.0.1:2402][0m
[mHTTP GET /evaluate 200 [0.04, 127.0.0.1:2402][0m
[mHTTP POST /evaluate 200 [0.04, 127.0.0.1:2409][0m
[mHTTP POST /evaluate 200 [0.03, 127.0.0.1:2421][0m
[mHTTP GET /admin/brewing/messurement/add/ 200 [0.14, 127.0.0.1:2421][0m
[mHTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:2421][0m
[32mHTTP POST /admin/brewing/messurement/add/ 302 [0.06, 127.0.0.1:2434][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.24, 127.0.0.1:2434][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:2434][0m
[mHTTP GET /evaluate 200 [0.04, 127.0.0.1:2434][0m
[mHTTP GET /evaluate 200 [0.19, 127.0.0.1:2822][0m
[mHTTP GET /evaluate 200 [0.09, 127.0.0.1:2857][0m
[mHTTP GET /evaluate 200 [0.06, 127.0.0.1:2877][0m
[mHTTP GET /evaluate 200 [0.07, 127.0.0.1:2900][0m
[mHTTP GET /evaluate 200 [0.05, 127.0.0.1:2994][0m
Not Found: /$bg-url
[33mHTTP GET /$bg-url 404 [0.19, 127.0.0.1:2994][0m
[mHTTP GET /evaluate 200 [0.04, 127.0.0.1:3019][0m
Not Found: /$bg-url
[33mHTTP GET /$bg-url 404 [0.05, 127.0.0.1:3019][0m
[mHTTP GET /evaluate 200 [0.04, 127.0.0.1:3072][0m
[mHTTP GET /evaluate 200 [0.31, 127.0.0.1:1038][0m
[mHTTP POST /evaluate 200 [0.07, 127.0.0.1:1061][0m
[mHTTP GET /evaluate 200 [0.09, 127.0.0.1:1115][0m
[mHTTP GET /evaluate 200 [0.17, 127.0.0.1:1132][0m
[mHTTP GET /evaluate 200 [0.06, 127.0.0.1:1041][0m
[mHTTP GET /evaluate 200 [0.06, 127.0.0.1:1065][0m
[mHTTP GET /evaluate 200 [0.07, 127.0.0.1:1143][0m
[mHTTP GET /evaluate 200 [0.33, 127.0.0.1:1161][0m
[mHTTP GET /evaluate 200 [0.07, 127.0.0.1:1173][0m
[mHTTP GET /evaluate 200 [0.07, 127.0.0.1:1258][0m
[mHTTP GET /evaluate 200 [0.08, 127.0.0.1:1282][0m
[mHTTP GET /evaluate 200 [0.05, 127.0.0.1:1292][0m
[mHTTP GET /evaluate 200 [0.07, 127.0.0.1:1297][0m
[mHTTP POST /evaluate 200 [0.47, 127.0.0.1:1315][0m
