[mHTTP GET / 200 [0.78, 127.0.0.1:17016][0m
[mHTTP GET /static/css/style.css 200 [0.07, 127.0.0.1:17016][0m
[mHTTP GET /static/css/login.css 200 [0.02, 127.0.0.1:17026][0m
[mHTTP GET /static/css/create.css 200 [0.03, 127.0.0.1:17026][0m
[mHTTP GET /static/css/brewing.css 200 [0.02, 127.0.0.1:17026][0m
[mHTTP GET /static/css/home.css 200 [0.04, 127.0.0.1:17026][0m
[mHTTP GET /static/css/template.css 200 [0.02, 127.0.0.1:17026][0m
[mHTTP GET /static/img/beer_background.webm 200 [1.11, 127.0.0.1:17026][0m
[mHTTP GET /static/img/favicon.ico 200 [1.12, 127.0.0.1:17027][0m
[mHTTP GET /home 200 [0.23, 127.0.0.1:17036][0m
[mHTTP GET /static/js/home.js 200 [0.81, 127.0.0.1:17039][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:17044][0m
[mHTTP GET /brewing 200 [0.18, 127.0.0.1:17044][0m
[mHTTP GET /static/js/three.js 200 [0.18, 127.0.0.1:17044][0m
[mHTTP GET /static/js/server_connection.js 200 [0.22, 127.0.0.1:17045][0m
[mHTTP GET /static/img/download.png 200 [0.07, 127.0.0.1:17044][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:17052]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:17052]
Fri Jun 10 09:59:59 2022: Another client connected
Exception inside application: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 51, in evaluate_response
    if(brew_system.next_step()):
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 93, in next_step
    self.initiate_maischen()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 192, in initiate_maischen
    phases = self.load_phases(0)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 166, in load_phases
    temp = json.loads(recipe.maischplan)[0][2]
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:17052]
[32mHTTP GET /admin 301 [0.06, 127.0.0.1:17147][0m
[mHTTP GET /admin/ 200 [0.71, 127.0.0.1:17147][0m
[mHTTP GET /static/admin/css/base.css 200 [0.10, 127.0.0.1:17147][0m
[mHTTP GET /static/admin/css/dark_mode.css 200 [0.16, 127.0.0.1:17148][0m
[mHTTP GET /static/admin/css/nav_sidebar.css 200 [0.05, 127.0.0.1:17147][0m
[mHTTP GET /static/admin/css/dashboard.css 200 [0.03, 127.0.0.1:17148][0m
[mHTTP GET /static/admin/css/responsive.css 200 [0.05, 127.0.0.1:17147][0m
[mHTTP GET /static/admin/js/nav_sidebar.js 200 [0.02, 127.0.0.1:17147][0m
[mHTTP GET /static/admin/css/fonts.css 200 [0.03, 127.0.0.1:17147][0m
[mHTTP GET /static/admin/img/icon-addlink.svg 200 [0.02, 127.0.0.1:17147][0m
[mHTTP GET /static/admin/img/icon-changelink.svg 200 [0.02, 127.0.0.1:17147][0m
[mHTTP GET /static/admin/img/icon-deletelink.svg 200 [0.02, 127.0.0.1:17147][0m
[mHTTP GET /static/admin/fonts/Roboto-Light-webfont.woff 200 [0.02, 127.0.0.1:17147][0m
[mHTTP GET /static/admin/fonts/Roboto-Bold-webfont.woff 200 [0.06, 127.0.0.1:17160][0m
[mHTTP GET /static/admin/fonts/Roboto-Regular-webfont.woff 200 [0.09, 127.0.0.1:17161][0m
Not Found: /favicon.ico
[33mHTTP GET /favicon.ico 404 [0.11, 127.0.0.1:17161][0m
[mHTTP GET /admin/brewing/brew_recipe/ 200 [0.45, 127.0.0.1:17168][0m
[mHTTP GET /static/admin/css/changelists.css 200 [0.05, 127.0.0.1:17168][0m
[mHTTP GET /admin/jsi18n/ 200 [0.14, 127.0.0.1:17169][0m
[mHTTP GET /static/admin/js/jquery.init.js 200 [0.04, 127.0.0.1:17169][0m
[mHTTP GET /static/admin/js/core.js 200 [0.07, 127.0.0.1:17176][0m
[mHTTP GET /static/admin/js/admin/RelatedObjectLookups.js 200 [0.16, 127.0.0.1:17177][0m
[mHTTP GET /static/admin/js/actions.js 200 [0.21, 127.0.0.1:17178][0m
[mHTTP GET /static/admin/js/urlify.js 200 [0.25, 127.0.0.1:17179][0m
Exception inside application: Single thread executor already being used, would deadlock
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 40, in __call__
    return await self.staticfiles_handler_class()(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 56, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\http.py", line 198, in __call__
    await self.handle(scope, async_to_sync(send), body_stream)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 382, in __call__
    raise RuntimeError(
RuntimeError: Single thread executor already being used, would deadlock
[35;1mHTTP GET /static/admin/js/vendor/jquery/jquery.js 500 [0.55, 127.0.0.1:17168][0m
[mHTTP GET /static/admin/js/prepopulate.js 200 [0.22, 127.0.0.1:17169][0m
[mHTTP GET /static/admin/js/vendor/xregexp/xregexp.js 200 [0.30, 127.0.0.1:17176][0m
[mHTTP GET /static/admin/img/tooltag-add.svg 200 [0.01, 127.0.0.1:17176][0m
[mHTTP GET /admin/brewing/brew_recipe/20/change/ 200 [0.55, 127.0.0.1:17176][0m
[mHTTP GET /static/admin/css/forms.css 200 [0.05, 127.0.0.1:17176][0m
[mHTTP GET /admin/jsi18n/ 200 [0.12, 127.0.0.1:17169][0m
[mHTTP GET /static/admin/js/vendor/jquery/jquery.js 200 [0.24, 127.0.0.1:17168][0m
[mHTTP GET /static/admin/js/prepopulate_init.js 200 [0.29, 127.0.0.1:17179][0m
[mHTTP GET /static/admin/css/widgets.css 200 [0.04, 127.0.0.1:17179][0m
[mHTTP GET /static/admin/js/change_form.js 200 [0.03, 127.0.0.1:17179][0m
[32mHTTP POST /admin/brewing/brew_recipe/20/change/ 302 [0.10, 127.0.0.1:17261][0m
[mHTTP GET /admin/brewing/brew_recipe/20/change/ 200 [0.82, 127.0.0.1:17261][0m
[mHTTP GET /admin/jsi18n/ 200 [0.10, 127.0.0.1:17261][0m
[mHTTP GET /static/admin/img/icon-yes.svg 200 [0.02, 127.0.0.1:17268][0m
[mHTTP GET /home 200 [0.09, 127.0.0.1:17275][0m
[32mHTTP POST /brewing 302 [0.06, 127.0.0.1:17275][0m
[mHTTP GET /brewing 200 [0.07, 127.0.0.1:17275][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:17283]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:17283]
Fri Jun 10 10:03:09 2022: Another client connected
[mHTTP GET /home 200 [0.35, 127.0.0.1:17370][0m
[32mHTTP POST /brewing 302 [0.06, 127.0.0.1:17381][0m
[mHTTP GET /brewing 200 [0.10, 127.0.0.1:17381][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:17386]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:17386]
Fri Jun 10 10:04:30 2022: Another client connected
[32mHTTP POST /admin/brewing/brew_recipe/20/change/ 302 [0.10, 127.0.0.1:17431][0m
[mHTTP GET /admin/brewing/brew_recipe/20/change/ 200 [0.52, 127.0.0.1:17431][0m
[mHTTP GET /admin/jsi18n/ 200 [0.22, 127.0.0.1:17431][0m
[mHTTP GET /brewing 200 [0.12, 127.0.0.1:17431][0m
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:17386]
[32mHTTP POST /brewing 302 [0.12, 127.0.0.1:17440][0m
[mHTTP GET /brewing 200 [0.08, 127.0.0.1:17440][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:17444]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:17444]
Fri Jun 10 10:05:39 2022: Another client connected
[mHTTP GET /brewing 200 [0.55, 127.0.0.1:17847][0m
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:17444]
[32mHTTP POST /brewing 302 [0.05, 127.0.0.1:17941][0m
[mHTTP GET /brewing 200 [0.08, 127.0.0.1:17941][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:17947]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:17947]
Fri Jun 10 10:14:26 2022: Another client connected
[mHTTP GET /brewing 200 [0.10, 127.0.0.1:17953][0m
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:17947]
[mHTTP GET /static/css/style.css 200 [0.26, 127.0.0.1:17953][0m
[mHTTP GET /static/css/login.css 200 [0.02, 127.0.0.1:17953][0m
[mHTTP GET /static/js/three.js 200 [0.06, 127.0.0.1:17953][0m
[mHTTP GET /static/js/server_connection.js 200 [0.07, 127.0.0.1:17954][0m
[mHTTP GET /static/css/create.css 200 [0.06, 127.0.0.1:17954][0m
[mHTTP GET /static/css/brewing.css 200 [0.02, 127.0.0.1:17954][0m
[mHTTP GET /static/img/download.png 200 [0.04, 127.0.0.1:17954][0m
[mHTTP GET /static/css/home.css 200 [0.06, 127.0.0.1:17953][0m
[mHTTP GET /static/css/template.css 200 [0.03, 127.0.0.1:17953][0m
[mHTTP GET /static/img/favicon.ico 200 [0.08, 127.0.0.1:17953][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:17965]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:17965]
Fri Jun 10 10:14:32 2022: Another client connected
[mHTTP GET /static/img/favicon.ico 200 [0.03, 127.0.0.1:17968][0m
[mHTTP GET /brewing 200 [0.38, 127.0.0.1:18272][0m
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:17965]
[32mHTTP POST /brewing 302 [0.05, 127.0.0.1:18280][0m
[mHTTP GET /brewing 200 [0.08, 127.0.0.1:18280][0m
[mHTTP GET /static/js/server_connection.js 200 [0.06, 127.0.0.1:18280][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:18286]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:18286]
Fri Jun 10 10:21:08 2022: Another client connected
[mHTTP GET /brewing 200 [0.16, 127.0.0.1:18405][0m
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:18286]
[mHTTP GET / 200 [0.14, 127.0.0.1:50738][0m
[mHTTP GET /static/css/style.css 200 [0.03, 127.0.0.1:50738][0m
[mHTTP GET /static/css/login.css 200 [0.05, 127.0.0.1:50738][0m
[mHTTP GET /static/css/create.css 200 [0.03, 127.0.0.1:50738][0m
[mHTTP GET /static/css/brewing.css 200 [0.03, 127.0.0.1:50738][0m
[mHTTP GET /static/css/home.css 200 [0.01, 127.0.0.1:50738][0m
[mHTTP GET /static/css/template.css 200 [0.02, 127.0.0.1:50738][0m
[mHTTP GET /static/img/beer_background.webm 200 [0.75, 127.0.0.1:50738][0m
[mHTTP GET /static/img/favicon.ico 200 [0.79, 127.0.0.1:50739][0m
[32mHTTP GET /home 302 [0.12, 127.0.0.1:50760][0m
[mHTTP GET /login 200 [0.08, 127.0.0.1:50760][0m
[32mHTTP POST /login 302 [0.52, 127.0.0.1:50773][0m
[mHTTP GET /home 200 [0.10, 127.0.0.1:50773][0m
[mHTTP GET /static/js/home.js 200 [0.03, 127.0.0.1:50773][0m
[32mHTTP POST /brewing 302 [0.07, 127.0.0.1:50781][0m
[mHTTP GET /brewing 200 [0.44, 127.0.0.1:50781][0m
[mHTTP GET /static/js/three.js 200 [0.30, 127.0.0.1:50781][0m
[mHTTP GET /static/js/server_connection.js 200 [0.32, 127.0.0.1:50782][0m
[mHTTP GET /static/img/download.png 200 [0.09, 127.0.0.1:50797][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:50799]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:50799]
Tue Jun 28 13:54:48 2022: Another client connected
Exception inside application: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 51, in evaluate_response
    if(brew_system.next_step()):
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 93, in next_step
    self.initiate_maischen()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 192, in initiate_maischen
    phases = self.load_phases(0)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 166, in load_phases
    temp = json.loads(recipe.maischplan)[0][2]
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:50799]
[mHTTP GET /brewing 200 [0.08, 127.0.0.1:50847][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:50852]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:50852]
Tue Jun 28 13:55:35 2022: Another client connected
[mHTTP GET /brewing 200 [0.24, 127.0.0.1:50898][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:50898][0m
[mHTTP GET /brewing 200 [0.14, 127.0.0.1:50898][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:50915]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:50915]
Tue Jun 28 13:56:18 2022: Another client connected
Exception inside application: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 51, in evaluate_response
    if(brew_system.next_step()):
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 93, in next_step
    self.initiate_maischen()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 192, in initiate_maischen
    phases = self.load_phases(0)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 166, in load_phases
    temp = json.loads(recipe.maischplan)[0][2]
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:50915]
[32mHTTP GET /admin 301 [0.19, 127.0.0.1:51028][0m
[mHTTP GET /admin/ 200 [0.77, 127.0.0.1:51028][0m
[mHTTP GET /static/admin/css/base.css 200 [0.10, 127.0.0.1:51028][0m
[mHTTP GET /static/admin/css/dark_mode.css 200 [0.16, 127.0.0.1:51030][0m
[mHTTP GET /static/admin/css/nav_sidebar.css 200 [0.07, 127.0.0.1:51028][0m
[mHTTP GET /static/admin/css/dashboard.css 200 [0.05, 127.0.0.1:51030][0m
[mHTTP GET /static/admin/css/responsive.css 200 [0.06, 127.0.0.1:51028][0m
[mHTTP GET /static/admin/css/fonts.css 200 [0.03, 127.0.0.1:51045][0m
[mHTTP GET /static/admin/js/nav_sidebar.js 200 [0.13, 127.0.0.1:51046][0m
[mHTTP GET /static/admin/img/icon-addlink.svg 200 [0.09, 127.0.0.1:51045][0m
[mHTTP GET /static/admin/img/icon-changelink.svg 200 [0.05, 127.0.0.1:51046][0m
[mHTTP GET /static/admin/img/icon-deletelink.svg 200 [0.04, 127.0.0.1:51045][0m
[mHTTP GET /static/admin/fonts/Roboto-Light-webfont.woff 200 [0.03, 127.0.0.1:51045][0m
[mHTTP GET /static/admin/fonts/Roboto-Bold-webfont.woff 200 [0.06, 127.0.0.1:51046][0m
[mHTTP GET /static/admin/fonts/Roboto-Regular-webfont.woff 200 [0.08, 127.0.0.1:51049][0m
Not Found: /favicon.ico
[33mHTTP GET /favicon.ico 404 [0.10, 127.0.0.1:51049][0m
[mHTTP GET /admin/brewing/brew_recipe/ 200 [0.44, 127.0.0.1:51049][0m
[mHTTP GET /static/admin/css/changelists.css 200 [0.04, 127.0.0.1:51049][0m
[mHTTP GET /admin/jsi18n/ 200 [0.09, 127.0.0.1:51046][0m
[mHTTP GET /static/admin/js/vendor/jquery/jquery.js 200 [0.14, 127.0.0.1:51045][0m
[mHTTP GET /static/admin/js/jquery.init.js 200 [0.17, 127.0.0.1:51050][0m
[mHTTP GET /static/admin/js/core.js 200 [0.19, 127.0.0.1:51051][0m
[mHTTP GET /static/admin/js/admin/RelatedObjectLookups.js 200 [0.19, 127.0.0.1:51049][0m
[mHTTP GET /static/admin/js/actions.js 200 [0.18, 127.0.0.1:51046][0m
[mHTTP GET /static/admin/js/urlify.js 200 [0.14, 127.0.0.1:51045][0m
[mHTTP GET /static/admin/js/prepopulate.js 200 [0.15, 127.0.0.1:51050][0m
[mHTTP GET /static/admin/js/vendor/xregexp/xregexp.js 200 [0.19, 127.0.0.1:51051][0m
[mHTTP GET /static/admin/img/tooltag-add.svg 200 [0.02, 127.0.0.1:51070][0m
[mHTTP GET /admin/brewing/brew_recipe/20/change/ 200 [0.58, 127.0.0.1:51070][0m
[mHTTP GET /static/admin/css/forms.css 200 [0.03, 127.0.0.1:51070][0m
[mHTTP GET /static/admin/js/prepopulate_init.js 200 [0.07, 127.0.0.1:51071][0m
[mHTTP GET /admin/jsi18n/ 200 [0.06, 127.0.0.1:51070][0m
[mHTTP GET /static/admin/css/widgets.css 200 [0.03, 127.0.0.1:51070][0m
[mHTTP GET /static/admin/js/change_form.js 200 [0.02, 127.0.0.1:51071][0m
[mHTTP GET /admin/brewing/brew_recipe/ 200 [0.35, 127.0.0.1:51087][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:51087][0m
[mHTTP GET /admin/brewing/brew_recipe/19/change/ 200 [0.45, 127.0.0.1:51087][0m
[mHTTP GET /admin/jsi18n/ 200 [0.06, 127.0.0.1:51087][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.62, 127.0.0.1:51204][0m
[32mHTTP POST /brewing 302 [0.05, 127.0.0.1:51218][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:51218][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:51222]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:51222]
Tue Jun 28 14:00:25 2022: Another client connected
Exception inside application: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 51, in evaluate_response
    if(brew_system.next_step()):
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 93, in next_step
    self.initiate_maischen()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 194, in initiate_maischen
    phases = self.load_phases(0)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 168, in load_phases
    temp = json.loads(recipe.maischplan)[0][2]
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:51222]
[mHTTP GET /admin/brewing/brew_recipe/ 200 [0.26, 127.0.0.1:51276][0m
[mHTTP GET /admin/jsi18n/ 200 [0.09, 127.0.0.1:51276][0m
[mHTTP GET /admin/brewing/brew_recipe/20/change/ 200 [0.43, 127.0.0.1:51284][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:51284][0m
[mHTTP GET /admin/brewing/brew_recipe/ 200 [0.15, 127.0.0.1:51304][0m
[mHTTP GET /admin/jsi18n/ 200 [0.06, 127.0.0.1:51304][0m
[mHTTP GET /admin/brewing/brew_recipe/19/change/ 200 [0.52, 127.0.0.1:51304][0m
[mHTTP GET /admin/jsi18n/ 200 [0.06, 127.0.0.1:51304][0m
[32mHTTP POST /admin/brewing/brew_recipe/19/change/ 302 [0.07, 127.0.0.1:51319][0m
[mHTTP GET /admin/brewing/brew_recipe/ 200 [0.16, 127.0.0.1:51319][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:51319][0m
[mHTTP GET /static/admin/img/icon-yes.svg 200 [0.02, 127.0.0.1:51319][0m
[mHTTP GET /brewing 200 [0.21, 127.0.0.1:51365][0m
[32mHTTP POST /brewing 302 [0.06, 127.0.0.1:51365][0m
[mHTTP GET /brewing 200 [0.07, 127.0.0.1:51365][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:51377]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:51377]
Tue Jun 28 14:02:00 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:51995]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:51995]
Tue Jun 28 16:07:31 2022: Another client connected
[mHTTP GET /home 200 [0.17, 127.0.0.1:1958][0m
[36mHTTP GET /static/css/style.css 304 [0.03, 127.0.0.1:1958][0m
[mHTTP GET /static/js/home.js 200 [0.07, 127.0.0.1:1959][0m
[mHTTP GET /static/css/login.css 200 [0.02, 127.0.0.1:1959][0m
[mHTTP GET /static/css/create.css 200 [0.04, 127.0.0.1:1959][0m
[mHTTP GET /static/css/brewing.css 200 [0.02, 127.0.0.1:1959][0m
[mHTTP GET /static/css/home.css 200 [0.02, 127.0.0.1:1959][0m
[mHTTP GET /static/css/template.css 200 [0.02, 127.0.0.1:1959][0m
[32mHTTP POST /brewing 302 [0.05, 127.0.0.1:1968][0m
[mHTTP GET /brewing 200 [0.09, 127.0.0.1:1968][0m
[mHTTP GET /static/img/download.png 200 [0.05, 127.0.0.1:1968][0m
[mHTTP GET /static/js/three.js 200 [0.31, 127.0.0.1:1969][0m
[mHTTP GET /static/js/server_connection.js 200 [0.31, 127.0.0.1:1968][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:1980]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:1980]
Thu Jun 30 19:59:08 2022: Another client connected
Exception inside application: 'brew_server' object has no attribute 'kochen'
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 189, in keep_process
    self.kochen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 135, in kochen_procedure
    if(time.time() > self.kochen["end"]):
AttributeError: 'brew_server' object has no attribute 'kochen'
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:1980]
[mHTTP GET /brewing 200 [0.07, 127.0.0.1:2015][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2018]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2018]
Thu Jun 30 19:59:39 2022: Another client connected
Exception inside application: 'brew_server' object has no attribute 'kochen'
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 189, in keep_process
    self.kochen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 135, in kochen_procedure
    if(time.time() > self.kochen["end"]):
AttributeError: 'brew_server' object has no attribute 'kochen'
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:2018]
[mHTTP GET /brewing 200 [0.10, 127.0.0.1:2022][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2027]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2027]
Thu Jun 30 19:59:47 2022: Another client connected
Exception inside application: 'brew_server' object has no attribute 'kochen'
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 189, in keep_process
    self.kochen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 135, in kochen_procedure
    if(time.time() > self.kochen["end"]):
AttributeError: 'brew_server' object has no attribute 'kochen'
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:2027]
[mHTTP GET /brewing 200 [0.07, 127.0.0.1:2022][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2036]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2036]
Thu Jun 30 19:59:55 2022: Another client connected
Exception inside application: 'brew_server' object has no attribute 'kochen'
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 189, in keep_process
    self.kochen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 135, in kochen_procedure
    if(time.time() > self.kochen["end"]):
AttributeError: 'brew_server' object has no attribute 'kochen'
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:2036]
[32mHTTP GET /admin 301 [0.02, 127.0.0.1:2088][0m
[mHTTP GET /admin/ 200 [0.25, 127.0.0.1:2088][0m
[mHTTP GET /static/admin/css/base.css 200 [0.03, 127.0.0.1:2088][0m
[mHTTP GET /static/admin/css/dark_mode.css 200 [0.10, 127.0.0.1:2089][0m
[mHTTP GET /static/admin/css/nav_sidebar.css 200 [0.09, 127.0.0.1:2088][0m
[mHTTP GET /static/admin/css/dashboard.css 200 [0.08, 127.0.0.1:2089][0m
[mHTTP GET /static/admin/css/responsive.css 200 [0.03, 127.0.0.1:2088][0m
[mHTTP GET /static/admin/js/nav_sidebar.js 200 [0.03, 127.0.0.1:2088][0m
[mHTTP GET /static/admin/css/fonts.css 200 [0.04, 127.0.0.1:2088][0m
[mHTTP GET /static/admin/img/icon-addlink.svg 200 [0.02, 127.0.0.1:2088][0m
[mHTTP GET /static/admin/img/icon-changelink.svg 200 [0.05, 127.0.0.1:2089][0m
[mHTTP GET /static/admin/img/icon-deletelink.svg 200 [0.08, 127.0.0.1:2094][0m
[mHTTP GET /static/admin/fonts/Roboto-Light-webfont.woff 200 [0.03, 127.0.0.1:2102][0m
[mHTTP GET /static/admin/fonts/Roboto-Bold-webfont.woff 200 [0.05, 127.0.0.1:2103][0m
[mHTTP GET /static/admin/fonts/Roboto-Regular-webfont.woff 200 [0.08, 127.0.0.1:2104][0m
Not Found: /favicon.ico
[33mHTTP GET /favicon.ico 404 [0.14, 127.0.0.1:2104][0m
[mHTTP GET /admin/brewing/brew_recipe/ 200 [0.27, 127.0.0.1:2104][0m
[mHTTP GET /static/admin/css/changelists.css 200 [0.06, 127.0.0.1:2104][0m
[mHTTP GET /admin/jsi18n/ 200 [0.10, 127.0.0.1:2103][0m
[mHTTP GET /static/admin/js/vendor/jquery/jquery.js 200 [0.27, 127.0.0.1:2102][0m
[mHTTP GET /static/admin/js/jquery.init.js 200 [0.31, 127.0.0.1:2105][0m
[mHTTP GET /static/admin/js/core.js 200 [0.39, 127.0.0.1:2104][0m
[mHTTP GET /static/admin/js/admin/RelatedObjectLookups.js 200 [0.38, 127.0.0.1:2103][0m
[mHTTP GET /static/admin/js/actions.js 200 [0.21, 127.0.0.1:2111][0m
[mHTTP GET /static/admin/js/urlify.js 200 [0.25, 127.0.0.1:2112][0m
[mHTTP GET /static/admin/js/prepopulate.js 200 [0.22, 127.0.0.1:2105][0m
[mHTTP GET /static/admin/js/vendor/xregexp/xregexp.js 200 [0.28, 127.0.0.1:2104][0m
[mHTTP GET /static/admin/img/tooltag-add.svg 200 [0.02, 127.0.0.1:2104][0m
[mHTTP GET /admin/brewing/brew_recipe/20/change/ 200 [0.45, 127.0.0.1:2104][0m
[mHTTP GET /static/admin/css/forms.css 200 [0.05, 127.0.0.1:2104][0m
[mHTTP GET /static/admin/js/prepopulate_init.js 200 [0.10, 127.0.0.1:2105][0m
[mHTTP GET /admin/jsi18n/ 200 [0.13, 127.0.0.1:2112][0m
[mHTTP GET /static/admin/css/widgets.css 200 [0.02, 127.0.0.1:2112][0m
[mHTTP GET /static/admin/js/change_form.js 200 [0.04, 127.0.0.1:2105][0m
[mHTTP GET /home 200 [0.06, 127.0.0.1:2131][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:2141][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:2141][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2144]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2144]
Thu Jun 30 20:01:00 2022: Another client connected
Exception inside application: 'brew_server' object has no attribute 'kochen'
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 189, in keep_process
    self.kochen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 135, in kochen_procedure
    if(time.time() > self.kochen["end"]):
AttributeError: 'brew_server' object has no attribute 'kochen'
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:2144]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.22, 127.0.0.1:2240][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:2246][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:2246][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2250]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2250]
Thu Jun 30 20:02:42 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py changed, reloading.
[mHTTP GET /brewing 200 [0.26, 127.0.0.1:2592][0m
[32mHTTP POST /brewing 302 [0.05, 127.0.0.1:2592][0m
[mHTTP GET /brewing 200 [0.08, 127.0.0.1:2592][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2606]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2606]
Thu Jun 30 20:07:49 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py changed, reloading.
[mHTTP GET /brewing 200 [0.26, 127.0.0.1:2842][0m
[32mHTTP POST /brewing 302 [0.03, 127.0.0.1:2864][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:2864][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2869]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2869]
Thu Jun 30 20:12:04 2022: Another client connected
[mHTTP GET /admin/brewing/brew_recipe/20/change/ 200 [3.22, 127.0.0.1:3270][0m
[mHTTP GET /admin/jsi18n/ 200 [0.11, 127.0.0.1:3282][0m
[mHTTP GET /brewing 200 [0.63, 127.0.0.1:3716][0m
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:2869]
[mHTTP GET /static/js/createPDF.js 200 [0.32, 127.0.0.1:3724][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:3728]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:3728]
Thu Jun 30 20:27:16 2022: Another client connected
[mHTTP GET /brewing 200 [0.20, 127.0.0.1:3820][0m
[32mHTTP POST /brewing 302 [0.05, 127.0.0.1:3841][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:3841][0m
[36mHTTP GET /static/js/createPDF.js 304 [0.03, 127.0.0.1:3847][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:3850]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:3850]
Thu Jun 30 20:28:20 2022: Another client connected
